fix(boot): crash the pod if cluster join failed

diff --git a/rootfs/bin/boot b/rootfs/bin/boot
--- a/rootfs/bin/boot
+++ b/rootfs/bin/boot
@@ -44,6 +44,10 @@ if ! $(env | grep -q "RIAK_MASTER=1"); then
   sleep $RIAK_JOIN_WAIT_TIME
   echo "Joining to cluster with IP ${CLUSTER_IP}"
   riak-admin cluster join "riak@${CLUSTER_IP}"
+  if [ "$?" != "0" ]; then
+    echo "cluster join failed with code $?, exiting"
+    exit $?
+  fi
 fi
 
 wait
